// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// run_thread
void run_thread();
RcppExport SEXP _AltPtr_run_thread() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    run_thread();
    return R_NilValue;
END_RCPP
}
// stop_thread
void stop_thread();
RcppExport SEXP _AltPtr_stop_thread() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    stop_thread();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AltPtr_run_thread", (DL_FUNC) &_AltPtr_run_thread, 0},
    {"_AltPtr_stop_thread", (DL_FUNC) &_AltPtr_stop_thread, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_AltPtr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
