// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_make_altPtr_from_altrep
SEXP C_make_altPtr_from_altrep(SEXP x);
RcppExport SEXP _Travel_C_make_altPtr_from_altrep(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_make_altPtr_from_altrep(x));
    return rcpp_result_gen;
END_RCPP
}
// C_getAltData1
SEXP C_getAltData1(SEXP x);
RcppExport SEXP _Travel_C_getAltData1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_getAltData1(x));
    return rcpp_result_gen;
END_RCPP
}
// C_getAltData2
SEXP C_getAltData2(SEXP x);
RcppExport SEXP _Travel_C_getAltData2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_getAltData2(x));
    return rcpp_result_gen;
END_RCPP
}
// print_value
void print_value(SEXP x);
RcppExport SEXP _Travel_print_value(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    print_value(x);
    return R_NilValue;
END_RCPP
}
// C_get_ptr
SEXP C_get_ptr(SEXP x);
RcppExport SEXP _Travel_C_get_ptr(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_get_ptr(x));
    return rcpp_result_gen;
END_RCPP
}
// C_make_fake_file
void C_make_fake_file(size_t size);
RcppExport SEXP _Travel_C_make_fake_file(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type size(sizeSEXP);
    C_make_fake_file(size);
    return R_NilValue;
END_RCPP
}
// filesystem_thread_func
void filesystem_thread_func();
RcppExport SEXP _Travel_filesystem_thread_func() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    filesystem_thread_func();
    return R_NilValue;
END_RCPP
}
// C_list_virtual_files
Rcpp::DataFrame C_list_virtual_files();
RcppExport SEXP _Travel_C_list_virtual_files() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(C_list_virtual_files());
    return rcpp_result_gen;
END_RCPP
}
// run_filesystem_thread_func
void run_filesystem_thread_func();
RcppExport SEXP _Travel_run_filesystem_thread_func() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    run_filesystem_thread_func();
    return R_NilValue;
END_RCPP
}
// C_run_filesystem_thread
void C_run_filesystem_thread();
RcppExport SEXP _Travel_C_run_filesystem_thread() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    C_run_filesystem_thread();
    return R_NilValue;
END_RCPP
}
// C_stop_filesystem_thread
void C_stop_filesystem_thread();
RcppExport SEXP _Travel_C_stop_filesystem_thread() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    C_stop_filesystem_thread();
    return R_NilValue;
END_RCPP
}
// C_is_filesystem_running
bool C_is_filesystem_running();
RcppExport SEXP _Travel_C_is_filesystem_running() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(C_is_filesystem_running());
    return rcpp_result_gen;
END_RCPP
}
// show_thread_status
void show_thread_status();
RcppExport SEXP _Travel_show_thread_status() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    show_thread_status();
    return R_NilValue;
END_RCPP
}
// C_get_file_handle_number
size_t C_get_file_handle_number();
RcppExport SEXP _Travel_C_get_file_handle_number() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(C_get_file_handle_number());
    return rcpp_result_gen;
END_RCPP
}
// C_set_print_location
void C_set_print_location(SEXP x);
RcppExport SEXP _Travel_C_set_print_location(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    C_set_print_location(x);
    return R_NilValue;
END_RCPP
}
// C_get_print_location
SEXP C_get_print_location();
RcppExport SEXP _Travel_C_get_print_location() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(C_get_print_location());
    return rcpp_result_gen;
END_RCPP
}
// C_set_mountpoint
void C_set_mountpoint(SEXP path);
RcppExport SEXP _Travel_C_set_mountpoint(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type path(pathSEXP);
    C_set_mountpoint(path);
    return R_NilValue;
END_RCPP
}
// C_get_mountpoint
SEXP C_get_mountpoint();
RcppExport SEXP _Travel_C_get_mountpoint() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(C_get_mountpoint());
    return rcpp_result_gen;
END_RCPP
}
// initial_filesystem_log
void initial_filesystem_log();
RcppExport SEXP _Travel_initial_filesystem_log() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    initial_filesystem_log();
    return R_NilValue;
END_RCPP
}
// close_filesystem_log
void close_filesystem_log();
RcppExport SEXP _Travel_close_filesystem_log() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    close_filesystem_log();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Travel_C_make_altPtr_from_altrep", (DL_FUNC) &_Travel_C_make_altPtr_from_altrep, 1},
    {"_Travel_C_getAltData1", (DL_FUNC) &_Travel_C_getAltData1, 1},
    {"_Travel_C_getAltData2", (DL_FUNC) &_Travel_C_getAltData2, 1},
    {"_Travel_print_value", (DL_FUNC) &_Travel_print_value, 1},
    {"_Travel_C_get_ptr", (DL_FUNC) &_Travel_C_get_ptr, 1},
    {"_Travel_C_make_fake_file", (DL_FUNC) &_Travel_C_make_fake_file, 1},
    {"_Travel_filesystem_thread_func", (DL_FUNC) &_Travel_filesystem_thread_func, 0},
    {"_Travel_C_list_virtual_files", (DL_FUNC) &_Travel_C_list_virtual_files, 0},
    {"_Travel_run_filesystem_thread_func", (DL_FUNC) &_Travel_run_filesystem_thread_func, 0},
    {"_Travel_C_run_filesystem_thread", (DL_FUNC) &_Travel_C_run_filesystem_thread, 0},
    {"_Travel_C_stop_filesystem_thread", (DL_FUNC) &_Travel_C_stop_filesystem_thread, 0},
    {"_Travel_C_is_filesystem_running", (DL_FUNC) &_Travel_C_is_filesystem_running, 0},
    {"_Travel_show_thread_status", (DL_FUNC) &_Travel_show_thread_status, 0},
    {"_Travel_C_get_file_handle_number", (DL_FUNC) &_Travel_C_get_file_handle_number, 0},
    {"_Travel_C_set_print_location", (DL_FUNC) &_Travel_C_set_print_location, 1},
    {"_Travel_C_get_print_location", (DL_FUNC) &_Travel_C_get_print_location, 0},
    {"_Travel_C_set_mountpoint", (DL_FUNC) &_Travel_C_set_mountpoint, 1},
    {"_Travel_C_get_mountpoint", (DL_FUNC) &_Travel_C_get_mountpoint, 0},
    {"_Travel_initial_filesystem_log", (DL_FUNC) &_Travel_initial_filesystem_log, 0},
    {"_Travel_close_filesystem_log", (DL_FUNC) &_Travel_close_filesystem_log, 0},
    {NULL, NULL, 0}
};

void init_logical_class(DllInfo *dll);
void init_integer_class(DllInfo *dll);
void init_real_class(DllInfo *dll);
RcppExport void R_init_Travel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    init_logical_class(dll);
    init_integer_class(dll);
    init_real_class(dll);
}
