// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_set_mountpoint
void C_set_mountpoint(SEXP path);
RcppExport SEXP _Travel_C_set_mountpoint(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type path(pathSEXP);
    C_set_mountpoint(path);
    return R_NilValue;
END_RCPP
}
// C_get_mountpoint
SEXP C_get_mountpoint();
RcppExport SEXP _Travel_C_get_mountpoint() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(C_get_mountpoint());
    return rcpp_result_gen;
END_RCPP
}
// filesystem_thread_func
void filesystem_thread_func();
RcppExport SEXP _Travel_filesystem_thread_func() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    filesystem_thread_func();
    return R_NilValue;
END_RCPP
}
// C_run_filesystem_thread
void C_run_filesystem_thread();
RcppExport SEXP _Travel_C_run_filesystem_thread() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    C_run_filesystem_thread();
    return R_NilValue;
END_RCPP
}
// C_mmp
int C_mmp(SEXP path, size_t length, Rcpp::NumericVector ind, Rcpp::NumericVector v);
RcppExport SEXP _Travel_C_mmp(SEXP pathSEXP, SEXP lengthSEXP, SEXP indSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type path(pathSEXP);
    Rcpp::traits::input_parameter< size_t >::type length(lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ind(indSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(C_mmp(path, length, ind, v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Travel_C_set_mountpoint", (DL_FUNC) &_Travel_C_set_mountpoint, 1},
    {"_Travel_C_get_mountpoint", (DL_FUNC) &_Travel_C_get_mountpoint, 0},
    {"_Travel_filesystem_thread_func", (DL_FUNC) &_Travel_filesystem_thread_func, 0},
    {"_Travel_C_run_filesystem_thread", (DL_FUNC) &_Travel_C_run_filesystem_thread, 0},
    {"_Travel_C_mmp", (DL_FUNC) &_Travel_C_mmp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Travel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
