# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_make_altptr_from_altrep <- function(x) {
    .Call(`_Travel_C_make_altptr_from_altrep`, x)
}

C_getAltData1 <- function(x) {
    .Call(`_Travel_C_getAltData1`, x)
}

C_getAltData2 <- function(x) {
    .Call(`_Travel_C_getAltData2`, x)
}

print_value <- function(x) {
    invisible(.Call(`_Travel_print_value`, x))
}

C_get_ptr <- function(x) {
    .Call(`_Travel_C_get_ptr`, x)
}

C_flush_altrep <- function(x) {
    invisible(.Call(`_Travel_C_flush_altrep`, x))
}

C_get_file_name <- function(x) {
    .Call(`_Travel_C_get_file_name`, x)
}

C_get_file_path <- function(x) {
    .Call(`_Travel_C_get_file_path`, x)
}

C_get_altptr_cache <- function(x) {
    .Call(`_Travel_C_get_altptr_cache`, x)
}

C_test <- function() {
    invisible(.Call(`_Travel_C_test`))
}

C_get_virtual_file_list <- function() {
    .Call(`_Travel_C_get_virtual_file_list`)
}

run_filesystem_thread_func <- function() {
    invisible(.Call(`_Travel_run_filesystem_thread_func`))
}

C_run_filesystem_thread <- function() {
    invisible(.Call(`_Travel_C_run_filesystem_thread`))
}

C_stop_filesystem_thread <- function() {
    invisible(.Call(`_Travel_C_stop_filesystem_thread`))
}

C_is_filesystem_running <- function() {
    .Call(`_Travel_C_is_filesystem_running`)
}

show_thread_status <- function() {
    invisible(.Call(`_Travel_show_thread_status`))
}

C_get_file_handle_number <- function() {
    .Call(`_Travel_C_get_file_handle_number`)
}

C_set_print_location <- function(x) {
    invisible(.Call(`_Travel_C_set_print_location`, x))
}

C_get_print_location <- function() {
    .Call(`_Travel_C_get_print_location`)
}

C_set_mountpoint <- function(path) {
    invisible(.Call(`_Travel_C_set_mountpoint`, path))
}

C_get_mountpoint <- function() {
    .Call(`_Travel_C_get_mountpoint`)
}

C_make_test_integer_altrep <- function(n) {
    .Call(`_Travel_C_make_test_integer_altrep`, n)
}

C_make_fake_file <- function(size) {
    invisible(.Call(`_Travel_C_make_fake_file`, size))
}

C_make_fake_file2 <- function(size) {
    invisible(.Call(`_Travel_C_make_fake_file2`, size))
}

C_make_altptr_from_file <- function(path, type, length) {
    .Call(`_Travel_C_make_altptr_from_file`, path, type, length)
}

C_set_real_value <- function(x, i, v) {
    invisible(.Call(`_Travel_C_set_real_value`, x, i, v))
}

C_set_int_value <- function(x, i, v) {
    invisible(.Call(`_Travel_C_set_int_value`, x, i, v))
}

C_reset_int <- function(x) {
    invisible(.Call(`_Travel_C_reset_int`, x))
}

C_duplicate <- function(x) {
    .Call(`_Travel_C_duplicate`, x)
}

C_is_altrep <- function(x) {
    .Call(`_Travel_C_is_altrep`, x)
}

C_set_debug_print <- function(x) {
    invisible(.Call(`_Travel_C_set_debug_print`, x))
}

C_set_altrep_print <- function(x) {
    invisible(.Call(`_Travel_C_set_altrep_print`, x))
}

C_set_filesystem_print <- function(x) {
    invisible(.Call(`_Travel_C_set_filesystem_print`, x))
}

C_set_filesystem_log <- function(x) {
    invisible(.Call(`_Travel_C_set_filesystem_log`, x))
}

initial_filesystem_log <- function() {
    invisible(.Call(`_Travel_initial_filesystem_log`))
}

close_filesystem_log <- function() {
    invisible(.Call(`_Travel_close_filesystem_log`))
}

