# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_make_altPtr <- function(x, name) {
    .Call(`_Travel_C_make_altPtr`, x, name)
}

C_getAltData1 <- function(x) {
    .Call(`_Travel_C_getAltData1`, x)
}

C_getAltData2 <- function(x) {
    .Call(`_Travel_C_getAltData2`, x)
}

get_int_value <- function(x, i) {
    .Call(`_Travel_get_int_value`, x, i)
}

get_double_value <- function(x, i) {
    .Call(`_Travel_get_double_value`, x, i)
}

C_stop_filesystem_thread <- function() {
    invisible(.Call(`_Travel_C_stop_filesystem_thread`))
}

C_run_filesystem_thread <- function() {
    invisible(.Call(`_Travel_C_run_filesystem_thread`))
}

C_set_print_location <- function(x) {
    invisible(.Call(`_Travel_C_set_print_location`, x))
}

C_get_print_location <- function() {
    .Call(`_Travel_C_get_print_location`)
}

C_set_mountpoint <- function(path) {
    invisible(.Call(`_Travel_C_set_mountpoint`, path))
}

C_get_mountpoint <- function() {
    .Call(`_Travel_C_get_mountpoint`)
}

initial_print_file <- function() {
    invisible(.Call(`_Travel_initial_print_file`))
}

close_print_file <- function() {
    invisible(.Call(`_Travel_close_print_file`))
}

